### ISSUE TITLE
`Expression`-based task would be nice to have upstream

### ISSUE THREAD

**Issue by Rubonnek** [limbonaut/limboai#12]
An [Expression](https://docs.godotengine.org/en/stable/classes/class_expression.html#class-expression)-based task which could be used against agents to evaluate complex expressions that can't be handled by current tasks would be nice to have upstream. For my purposes it would be really nice to be able to call `Expression::execute` and store the result in the blackboard to later inspect it with `CheckVar` or `CheckTrigger`. For a ton of simple use cases, this eliminates the need to subclass and step into GDScript or `<InsertLangHere>` land -- allowing for faster prototyping straight through LimboAI.

The implementation would be virtually the same as `BTCallMethod`.

**Comment by limbonaut** [comment]
I think it would make a useful addition to the CheckX/SetX family of tasks.
One thing I would add is that the task should be able to take blackboard values as an input, i.e, we should be able to write `clampf(pow(speed, 2.0), 0.0, max_speed)` with `speed` and `max_speed` added as an input to the expression. User declares those vars in the `input_vars` array property. 
Another approach could be, instead of using the exported `input_vars` array, to pre-parse the expression in `_setup`, replacing `$variable_name` tokens with `variable_name` and registering them in a private collection.
