### ISSUE TITLE
CallAgentMethod?

### ISSUE THREAD

**Issue by andmish** [limbonaut/limboai#135]
I feel like calling agent's method quickly in a tree is really missing for convenience.

For now, we could make custom task that just calls agent's needed method (which needs creating new files), use `CallMethod` (for which we need to specify a node, which is redundant if it's always the agent), maybe make set/get property and use `SetAgentProperty`?
Everything needs extra steps, `CallAgentMethod` could simplify it and just call method directly on agent (behavior like `CallMethod`, minus node property, always the agent)

No? Maybe I'm missing some existing functionality that already works quick like that? 👀

![callagentmethod](https://github.com/limbonaut/limboai/assets/37307893/fe3f38b0-10c7-42f2-9d8f-e678b48f7755)

**Comment by limbonaut** [comment]
I think just defaulting `CallMethod` to agent would suffice without adding additional tasks to the core.

**Comment by andmish** [comment]
@limbonaut hmm, ok, I actually just now noticed something. Here is the explanation.

There is one workflow which I use myself (and I bet some other people too) and looks like it won't work.
If I design/create new enemy type (adding needed rays, areas, colliders, etc.), I usually don't save them as new scenes instantly. Instead, I just work in current level scene. Because it's much quicker to iterate and adjust things, rather than jumping between 2 scenes (and because for now you can't easily [resave/apply changes to instantiated scenes](https://github.com/godotengine/godot-proposals/issues/7649) in Godot). So imagine, I added new behavior for this new enemy and now I want a few more of the same enemies to test. So I quickly duplicate this node and just move them around in this level scene (later I can delete these extra nodes quickly too and continue to work on the first one)  

Now all the tasks that use node paths like `CallMethod` and all `Animations` states, won't work correctly.
Obviously the paths won't be updated on duplication and they all will be pointing to that first original enemy node.
While `SetAgentProperty` and `CheckAgentProperty` will still work because they are bounded to agent.

So this workflow is not possible, right? Is there a way to set paths in those tasks relative to agent node and not started from root node?

Also if you think `CallAgentMethod` would be redundant, then why there are `CheckAgentProperty`/`SetAgentProperty`, why not just make `CheckProperty`/`SetProperty` instead, which again can be linked to any node and agent itself, and which will broaden their use cases?

I think it's either they are grouped around Agent and Scene (and have doubles, like `CallMethod` and `CallAgentMethod`, which maybe is not great, I agree), or they all global scene-based where you can call methods/check properties of other nodes or agent. And also if you want you could specify in the task properties that path is relative to agent somehow (maybe checkbox "Relative to agent?") and then described workflow could work? 🤔

**Comment by limbonaut** [comment]
>  Is there a way to set paths in those tasks relative to agent node and not started from root node?

I didn't find a way to instruct inspector editor for NodePaths to edit the said path relative to anything else but scene root. Not to mention, that NodePath editor is not even accessible in GDExtension. So whichever scene is currently edited, its root is used by `NodePath` editor, even if that scene is unrelated to BT :shrug: . Thus, we're stuck with scene root.

> So this workflow is not possible, right?

Depends. You can use `BlackboardPlan` workflow to set paths relative to `BTPlayer/BTState`. Define a NodePath variable in the BT's blackboard plan, and assign its value in `BTPlayer`. That way, the path itself will be relative to `BTPlayer`. This is the recommended way of accessing scene objects. Relying on `NodePath`  in a BT, you create a coupling of that BT with a scene, which can become a problem, as you can see.

> Also if you think CallAgentMethod would be redundant, then why there are CheckAgentProperty/SetAgentProperty, why not just make CheckProperty/SetProperty instead, which again can be linked to any node and agent itself, and which will broaden their use cases?

Because it's a relict of the past. I haven't got time for that just yet. Ideally, there should be only one `SetProperty/CheckProperty` task pair (to be implemented).  `SetAgentProperty` is going to be deprecated eventually. Especially, when variable to property binding gets fully done.

> ... and have doubles, like CallMethod and CallAgentMethod ...

Following this logic, I would also have to add `CallVarMethod` for objects on the `Blackboard`. In the end of the day, we are talking about a parameter to `CallMethod`. Doubling and trippling each task that needs access to something related to objects will add bloat to the plugin, and increase cognitive load while browsing the task palette, and will add maintenance for me in the long run. Parametrizing `CallMethod` in such a way, that object could be specified regardless of the source, seems to me a better idea. Especially, if it can be repeated for other similar tasks. That's the whole point of `BBParam` classes, they just need a way to handle agent better.

**Comment by limbonaut** [comment]
This would be a welcome addition IMO:
![image](https://github.com/limbonaut/limboai/assets/2766569/0d81ea54-35a1-4b7e-b5a2-3d2f608d9c5e)
