### ISSUE TITLE
Android Export

### ISSUE THREAD

**Issue by AndromeDIE** [limbonaut/limboai#146]
Already posted this on the discord, but when I try to remote debug my project on a VR Headset via Android Export Preset I get this error message.
![image](https://github.com/limbonaut/limboai/assets/120034548/fcff7d23-924c-4ed0-b213-025ffd32b8f8)
Are Android Exports not supported yet?

**Comment by limbonaut** [comment]
Only module version is supported at the moment via custom templates. Currently, we don't build Android libraries for GDExtension. Simply because I didn't add that part to our GitHub build process yet. You could probably build those libs on your own, and I don't think there is any serious reason why it wouldn't be compatible. The module version already compiles with no issues so far.
