### ISSUE TITLE
Mac Builds are not opening on my Mac

### ISSUE THREAD

**Issue by dansingsinthereign** [limbonaut/limboai#6]
I've tried multiple builds (releases included) and for some reason I can't seem to open the file.
Would appreciate if you could look into it.

The application “Godot-2” can’t be opened. - is all it says. 
![Screen Shot 2023-12-16 at 9 37 44 pm](https://github.com/limbonaut/limboai/assets/114900912/317230ed-93bd-4f51-87d0-e0428ebec05e)

**Comment by limbonaut** [comment]
I have an idea why this might be happening, but I don't have a Mac to check it out.
There is an old issue with GitHub Actions uploader not preserving executable permissions when packing things as a ZIP artifact: https://github.com/actions/upload-artifact/issues/38
Since the builds are formed using GitHub Actions, those permissions might be not set, and they should be!

You can try the following steps:
1. Unpack the ZIP file with the Mac editor.
2. Set the  "Godot.app/Contents/MacOS/Godot" file as executable. If you are comfortable with the terminal you can do `chmod +x Godot.app/Contents/MacOS/Godot`.
3. Repack it back into a ZIP (with ".app" extension).

I did those steps on a v0.5 build using my Linux OS. Please, let me know if it works for you.
Link: https://drive.proton.me/urls/ZRT8DY1ZM4#0n4uiZWiTGYI

**Comment by limbonaut** [comment]
Try if this build works: https://github.com/limbonaut/limboai/actions/runs/7232557818

**Comment by dansingsinthereign** [comment]
I tried the build and it works like a charm! Excited to dig into this. Thanks

**Comment by limbonaut** [comment]
Cool. Then I'm closing it. 
If you have any questions, we got a Discord now.

**Comment by dansingsinthereign** [comment]
Thanks for the prompt response! The only problem now is if you're using Desktop, Documents, and Downloads folders, the permission request will keep popping up. But when I avoid those locations, no problem.

**Comment by limbonaut** [comment]
Maybe it happens because the binary is not signed. Perhaps, you could add it to some exceptions list? Don't have a Mac, sorry.

**Comment by dansingsinthereign** [comment]
Yeah the weird thing is I've done the exceptions but it still keeps popping up.
The solution of saving it else where (apart from Desktop, Documents and Downloads folders) work. So at this point it's all good for me :)
![Screen Shot 2023-12-17 at 9 25 28 am](https://github.com/limbonaut/limboai/assets/114900912/de456888-c3e6-49ba-97aa-a80ca57c0b8a)
