### ISSUE TITLE
guide to making limboai work in gdscript for a total beginner

### ISSUE THREAD

**Issue by wharryG** [limbonaut/limboai#83]
Hello, This is a really great addon and i would like to study how it works but i cant seem to grasp how to run this on gdscript? can someone make a guide(with pictures if possible) on how to use this? I got confused on the builds? running commands? clones? repositories?

Speaking from the perspective of someone new to github and godot.

Thanks in advance.

**Comment by limbonaut** [comment]
LimboAI can be used as an extension, or a custom engine build. With engine build, you need to download custom godot binaries, and use those instead of your regular Godot. With extension, you simply put extension in your project (just like any other addon), and use normal official Godot build (4.2.x is currently supported by LimboAI). The easiest start would be with extension. Here's a short guide for GDExtension: 

1) Make sure you're using Godot 4.2.1.
2) Create a new project for your experiments with LimboAI.
3) In Godot, click AssetLib tab at the top of the screen, and search for LimboAI. Download it. It will download LimboAI plugin and the demo project files.
4) Reload your project with `Project->Reload project`
5)  In the project files, locate a scene file called "showcase.tscn" and run it. It's a demo entry point.

To make your own behavior trees:
1) Make a scene file for your agent, or open existing scene. 
2) Add a node to your scene called `BTPlayer`.
3) Select `BTPlayer`, and create a new behavior tree in inspector.
4) Click the resource property to edit it.

I recommend exploring documentation after you experiment with the demo project. We also have Discord if you need assistance.

**Comment by ClayZH** [comment]
It doesn't work at all. The showcase scene get a bunch of error.

![error](https://github.com/limbonaut/limboai/assets/21108116/a8610a78-04f1-482d-8a8c-d23c21901912)

Totally fresh new project according to your guide. Godot 4.2.1, plugin version is 1.0.2

**Comment by limbonaut** [comment]
@ClayZH The patch-level version compatibility should be fixed now, thanks for reporting. You can either download the updated build in AssetLib or [from GitHub releases](https://github.com/limbonaut/limboai/releases/download/v1.0.2/limboai+v1.0.2.gdextension-4.2.zip).

**Comment by limbonaut** [comment]
I've added a short guide to the documentation (called First steps), and linked it in the README. Closing this issue.
